export const testimonialEditableFields = [
  { name: "title", label: "Заголовок", type: "text" },
  { name: "subtitle", label: "Подзаголовок", type: "text" },
  { name: "testimonial1Quote", label: "Отзыв 1", type: "text" },
  { name: "testimonial1Name", label: "Имя 1", type: "text" },
  { name: "testimonial1Role", label: "Должность 1", type: "text" },
  { name: "testimonial1Avatar", label: "Аватар 1 (эмодзи)", type: "text" },
  { name: "testimonial1Rating", label: "Рейтинг 1 (1-5)", type: "text" },
  { name: "testimonial2Quote", label: "Отзыв 2", type: "text" },
  { name: "testimonial2Name", label: "Имя 2", type: "text" },
  { name: "testimonial2Role", label: "Должность 2", type: "text" },
  { name: "testimonial2Avatar", label: "Аватар 2 (эмодзи)", type: "text" },
  { name: "testimonial2Rating", label: "Рейтинг 2 (1-5)", type: "text" },
  { name: "testimonial3Quote", label: "Отзыв 3", type: "text" },
  { name: "testimonial3Name", label: "Имя 3", type: "text" },
  { name: "testimonial3Role", label: "Должность 3", type: "text" },
  { name: "testimonial3Avatar", label: "Аватар 3 (эмодзи)", type: "text" },
  { name: "testimonial3Rating", label: "Рейтинг 3 (1-5)", type: "text" },
];
