import type { BlockData } from "../type/blocks";

export interface Template {
  id: string;
  name: string;
  description: string;
  thumbnail: string;
  category: string;
  blocks: BlockData[];
}

export const templates: Template[] = [
  {
    id: "startup",
    name: "Стартап",
    description: "Современный лендинг для технологического стартапа",
    thumbnail: "🚀",
    category: "Бизнес",
    blocks: [
      { type: "hero", variant: "hero-3", props: {
        title: "Инновационное решение для вашего бизнеса",
        description: "Мы создаем технологии будущего уже сегодня",
        buttonText: "Попробовать бесплатно",
        backgroundImage: "https://picsum.photos/800/600",
      }},
      { type: "feature", variant: "feature-2", props: {
        title: "Наши преимущества",
        feature1Title: "Быстро",
        feature1Description: "Молниеносная скорость работы",
        feature2Title: "Качественно",
        feature2Description: "Внимание к каждой детали",
        feature3Title: "Надежно",
        feature3Description: "Гарантия стабильной работы",
      }},
      { type: "benefit", variant: "benefit-1", props: {
        title: "Почему выбирают нас",
        benefit1Icon: "⚡",
        benefit1Title: "Скорость",
        benefit1Description: "Быстрая загрузка и отклик",
        benefit2Icon: "🎨",
        benefit2Title: "Дизайн",
        benefit2Description: "Современный и адаптивный",
        benefit3Icon: "🔧",
        benefit3Title: "Гибкость",
        benefit3Description: "Легкая настройка под себя",
      }},
      { type: "pricing", variant: "pricing-1", props: {
        title: "Тарифные планы",
        subtitle: "Выберите план, который подходит именно вам",
        plan1Name: "Старт",
        plan1Price: "0",
        plan1Features: "1 проект,Базовые функции,Email поддержка",
        plan1ButtonText: "Начать бесплатно",
        plan2Name: "Профи",
        plan2Price: "990",
        plan2Features: "10 проектов,Все функции,Приоритетная поддержка",
        plan2ButtonText: "Выбрать план",
        plan3Name: "Бизнес",
        plan3Price: "2990",
        plan3Features: "Безлимитно,Все функции,Персональный менеджер",
        plan3ButtonText: "Связаться с нами",
      }},
      { type: "testimonial", variant: "testimonial-1", props: {
        title: "Отзывы клиентов",
        subtitle: "Что говорят о нас наши клиенты",
        testimonial1Quote: "Отличный сервис! Команда превзошла все ожидания.",
        testimonial1Name: "Александр Петров",
        testimonial1Role: "CEO, TechCorp",
        testimonial1Avatar: "👨‍💼",
        testimonial1Rating: "5",
        testimonial2Quote: "Лучшее решение на рынке. Рекомендую всем!",
        testimonial2Name: "Мария Иванова",
        testimonial2Role: "Маркетолог, StartupX",
        testimonial2Avatar: "👩‍💼",
        testimonial2Rating: "5",
        testimonial3Quote: "Профессиональный подход и отличная поддержка.",
        testimonial3Name: "Дмитрий Сидоров",
        testimonial3Role: "Разработчик, WebStudio",
        testimonial3Avatar: "👨‍💻",
        testimonial3Rating: "5",
      }},
      { type: "cta", variant: "cta-1", props: {
        title: "Готовы начать?",
        description: "Присоединяйтесь к тысячам довольных клиентов уже сегодня",
        buttonText: "Начать сейчас",
      }},
      { type: "footer", variant: "footer-1", props: {
        brandName: "StartupX",
        brandDescription: "Создаем лучшие решения для вашего бизнеса с 2024 года.",
        brandLogo: "🚀",
        socialLinks: "twitter,facebook,instagram,linkedin",
        column1Title: "Продукт",
        column1Links: "Функции,Цены,Интеграции",
        column2Title: "Компания",
        column2Links: "О нас,Карьера,Блог",
        column3Title: "Поддержка",
        column3Links: "Помощь,Контакты,API",
        copyright: "© 2024 StartupX. Все права защищены.",
      }},
    ],
  },
  {
    id: "portfolio",
    name: "Портфолио",
    description: "Персональный сайт-портфолио для специалиста",
    thumbnail: "👨‍🎨",
    category: "Личное",
    blocks: [
      { type: "hero", variant: "hero-2", props: {
        title: "Привет, я Джон",
        description: "Веб-разработчик и UI/UX дизайнер",
        buttonText: "Смотреть работы",
      }},
      { type: "benefit", variant: "benefit-1", props: {
        title: "Мои навыки",
        benefit1Icon: "💻",
        benefit1Title: "Разработка",
        benefit1Description: "React, TypeScript, Node.js",
        benefit2Icon: "🎨",
        benefit2Title: "Дизайн",
        benefit2Description: "Figma, Adobe XD, Sketch",
        benefit3Icon: "📱",
        benefit3Title: "Mobile",
        benefit3Description: "React Native, Flutter",
      }},
      { type: "testimonial", variant: "testimonial-1", props: {
        title: "Отзывы клиентов",
        subtitle: "Что говорят о моей работе",
        testimonial1Quote: "Отличная работа! Все сроки соблюдены.",
        testimonial1Name: "Алексей К.",
        testimonial1Role: "CEO, Company",
        testimonial1Avatar: "👨‍💼",
        testimonial1Rating: "5",
        testimonial2Quote: "Профессиональный подход к делу.",
        testimonial2Name: "Мария П.",
        testimonial2Role: "Маркетолог",
        testimonial2Avatar: "👩‍💼",
        testimonial2Rating: "5",
        testimonial3Quote: "Буду обращаться еще!",
        testimonial3Name: "Иван С.",
        testimonial3Role: "Предприниматель",
        testimonial3Avatar: "👨‍💻",
        testimonial3Rating: "5",
      }},
      { type: "cta", variant: "cta-1", props: {
        title: "Давайте работать вместе!",
        description: "Открыт для новых проектов и предложений",
        buttonText: "Связаться со мной",
      }},
      { type: "footer", variant: "footer-1", props: {
        brandName: "John Doe",
        brandDescription: "Создаю цифровые продукты с душой",
        brandLogo: "👨‍🎨",
        socialLinks: "twitter,instagram,github,linkedin",
        column1Title: "Проекты",
        column1Links: "Портфолио,Кейсы,Отзывы",
        column2Title: "Инфо",
        column2Links: "Обо мне,Блог,Контакты",
        column3Title: "Соцсети",
        column3Links: "Twitter,Instagram,LinkedIn",
        copyright: "© 2024 John Doe. Все права защищены.",
      }},
    ],
  },
  {
    id: "product",
    name: "Продукт",
    description: "Лендинг для запуска нового продукта",
    thumbnail: "📦",
    category: "Бизнес",
    blocks: [
      { type: "hero", variant: "hero-1", props: {
        title: "Новый iPhone 16 Pro",
        description: "Технологии будущего в ваших руках",
        buttonText: "Предзаказ",
        backgroundImage: "https://picsum.photos/1920/1080",
      }},
      { type: "feature", variant: "feature-2", props: {
        title: "Особенности",
        feature1Title: "A18 Bionic",
        feature1Description: "Новейший процессор",
        feature2Title: "48 МП камера",
        feature2Description: "Профессиональная съемка",
        feature3Title: "24 часа",
        feature3Description: "Работы без подзарядки",
      }},
      { type: "pricing", variant: "pricing-1", props: {
        title: "Выберите модель",
        subtitle: "Доступны три версии",
        plan1Name: "128 ГБ",
        plan1Price: "79990",
        plan1Features: "6.1\" дисплей,Двойная камера,Face ID",
        plan1ButtonText: "Купить",
        plan2Name: "256 ГБ",
        plan2Price: "89990",
        plan2Features: "6.1\" дисплей,Тройная камера,Face ID",
        plan2ButtonText: "Купить",
        plan3Name: "512 ГБ",
        plan3Price: "109990",
        plan3Features: "6.7\" дисплей,Тройная камера,Face ID",
        plan3ButtonText: "Купить",
      }},
      { type: "footer", variant: "footer-1", props: {
        brandName: "Apple",
        brandDescription: "Инновации с 1976 года",
        brandLogo: "🍎",
        socialLinks: "twitter,facebook,youtube,instagram",
        column1Title: "Продукты",
        column1Links: "iPhone,iPad,Mac",
        column2Title: "Поддержка",
        column2Links: "Контакты,Сервис,Гарантия",
        column3Title: "Компания",
        column3Links: "О нас,Карьера,Пресс",
        copyright: "© 2024 Apple Inc. Все права защищены.",
      }},
    ],
  },
];

export const templateCategories = [
  "Все",
  "Бизнес",
  "Личное",
  "Магазин",
  "Ресторан",
  "Спорт",
];
