export const teamEditableFields = [
  { name: "title", label: "Заголовок", type: "text" },
  { name: "subtitle", label: "Подзаголовок", type: "text" },
  { name: "member1Name", label: "Имя 1", type: "text" },
  { name: "member1Role", label: "Должность 1", type: "text" },
  { name: "member1Bio", label: "Описание 1", type: "text" },
  { name: "member1Avatar", label: "Аватар 1 (эмодзи)", type: "text" },
  { name: "member1Socials", label: "Соцсети 1", type: "text" },
  { name: "member2Name", label: "Имя 2", type: "text" },
  { name: "member2Role", label: "Должность 2", type: "text" },
  { name: "member2Bio", label: "Описание 2", type: "text" },
  { name: "member2Avatar", label: "Аватар 2 (эмодзи)", type: "text" },
  { name: "member2Socials", label: "Соцсети 2", type: "text" },
  { name: "member3Name", label: "Имя 3", type: "text" },
  { name: "member3Role", label: "Должность 3", type: "text" },
  { name: "member3Bio", label: "Описание 3", type: "text" },
  { name: "member3Avatar", label: "Аватар 3 (эмодзи)", type: "text" },
  { name: "member3Socials", label: "Соцсети 3", type: "text" },
  { name: "member4Name", label: "Имя 4", type: "text" },
  { name: "member4Role", label: "Должность 4", type: "text" },
  { name: "member4Bio", label: "Описание 4", type: "text" },
  { name: "member4Avatar", label: "Аватар 4 (эмодзи)", type: "text" },
  { name: "member4Socials", label: "Соцсети 4", type: "text" },
];
